[config]
schemaVersion = "1.0.0"

[package]
namespace = "Binbin"
name = "Town_Map"
versionNumber = "1.0.0"
description = "A mod that lets to go to the Map from town and back to Town from the Map"
websiteUrl = "https://github.com/binbinmods/TownMap"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_AcrossTheObelisk = "5.4.23"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./TownMap"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]


